<a href="https://colab.research.google.com/github/timmcoll03/simpleAnalysis/blob/main/BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from keras.preprocessing.text import Tokenizer
from sklearn.cluster import KMeans
%matplotlib inline


In [2]:
train = pd.read_csv('/Users/timothycolledge/Desktop/Compsci/Project 3/simpleAnalysis/IMDB Dataset.csv',index_col=False)
train.head()
  

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
## Step 1: Determine the Vocabulary
tokenizer = Tokenizer()
tokenizer.fit_on_texts(train.review)
print(f'ListOfWords: {list(tokenizer.word_index.keys())}')



In [22]:
## Step 2: Count
display = tokenizer.texts_to_matrix(train.review[:100], mode='count')
print(display)

[[ 0. 16.  6. ...  0.  0.  0.]
 [ 0. 16.  7. ...  0.  0.  0.]
 [ 0.  8.  4. ...  0.  0.  0.]
 ...
 [ 0.  3.  6. ...  0.  0.  0.]
 [ 0.  6.  7. ...  0.  0.  0.]
 [ 0. 43. 13. ...  0.  0.  0.]]


In [23]:
df = pd.DataFrame(display)  
df.head()

0       1       2       3       4       5       6       7       8       \
0     0.0    16.0     6.0     3.0     7.0     6.0     9.0     6.0     3.0   
1     0.0    16.0     7.0     4.0     5.0     2.0     3.0     6.0     0.0   
2     0.0     8.0     4.0     6.0     4.0     4.0     4.0     4.0     4.0   
3     0.0     6.0     4.0    10.0     2.0     3.0     2.0     6.0     2.0   
4     0.0    20.0     5.0     6.0     6.0     7.0     7.0     8.0     6.0   

   9       ...  124243  124244  124245  124246  124247  124248  124249  \
0     6.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     3.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     2.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   124250  124251  124252  
0     0.0     0.0     0.0  
1     0.0     0.0     0.0  
2     0.0     0.0     0.0  
3     0.0     0.0     0.0  
4     0.0     0.0     0.0  

[5 rows x 124253 columns]

In [24]:
from sklearn.cluster import KMeans

In [25]:
kmeans = KMeans(n_clusters=2)
kmeans.fit(df)
print(kmeans.inertia_)

39187.09825195924


In [27]:
mf = pd.DataFrame(kmeans)
mf.head

ValueError: DataFrame constructor not properly called!

In [13]:
rf = pd.DataFrame(kmeans.cluster_centers_)
rf.head 

<bound method NDFrame.head of    0          1          2          3          4          5         6       \
0     0.0   9.556962   5.000000   5.367089   4.582278   3.772152  3.253165   
1     0.0  29.761905  12.190476  12.142857  12.476190  11.095238  7.714286   

     7         8         9       ...  124243  124244  124245  124246  124247  \
0  3.518987  2.772152  2.493671  ...     0.0     0.0     0.0     0.0     0.0   
1  8.571429  7.904762  4.047619  ...     0.0     0.0     0.0     0.0     0.0   

   124248  124249  124250  124251  124252  
0     0.0     0.0     0.0     0.0     0.0  
1     0.0     0.0     0.0     0.0     0.0  

[2 rows x 124253 columns]>

In [17]:
plt.plot(rf, 'ro')
plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

Error in callback <function flush_figures at 0x157e53280> (for post_execute):


KeyboardInterrupt: 

In [ ]:
cluster_map = pd.DataFrame()
cluster_map['data_index'] = df.index.values
cluster_map['cluster'] = kmeans.labels_
cluster_map.head()

data_index  cluster
0           0        2
1           1        2
2           2        0
3           3        2
4           4        2